/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameTeacher.java
 *
 * Created on 27-sept.-2009, 14:28:37
 */

package UI;

import java.awt.Cursor;
import java.io.*;
import java.sql.SQLException;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import pimpyteacher.*;

/**
 *
 * @author Alain
 */
public class JFrameTeacher extends javax.swing.JFrame {

    private GraphicalPimpyController controller = null;
    private ArrayList<String> sentences = null;
    private boolean saved = false;
    private File openedFile = null;
    private int cursor = 0;

    /** Creates new form JFrameTeacher */
    public JFrameTeacher(GraphicalPimpyController controller) {
        this.controller = controller;
        initComponents();
        disableControls();
    }

    private void enableControls() {
        this.jButtonNext.setEnabled(true);
        this.jButtonSave.setEnabled(true);
        this.jButtonPrevious.setEnabled(false);
        this.jButtonGoToPos.setEnabled(true);
        this.jTextFieldPos.setEnabled(true);
    }

    private void disableControls() {
        this.jButtonNext.setEnabled(false);
        this.jButtonPrevious.setEnabled(false);
        this.jButtonGoToPos.setEnabled(false);
        this.jTextFieldPos.setEnabled(false);
    }

    private void displayPrevious() {
        if (this.sentences.size() < 1) {
            this.disableControls();
            this.jLabelOpened.setText("None");
            return;
        }
        if (this.cursor < 2) {
            this.jButtonPrevious.setEnabled(false);
            return;
        }
        cursor -= 2;
        this.displayNext();
    }

    private void displayNext() {
        if (this.sentences == null) {
            this.disableControls();
            this.jLabelOpened.setText("None");
            return;
        }
        // We're using cursor to choose the message + answer to display.
        this.jTextAreaSubmitted.setText(this.sentences.get(cursor));
        if (this.sentences.size() > cursor + 1) {
            this.jTextAreaResponse.setText(this.sentences.get(cursor + 1));
        }
        this.jTextAreaContextResponse.setText("");
        this.jRadioButtonSentenceNormal.setSelected(true);
        cursor++;
        this.jTextFieldPos.setText(Integer.toString(cursor));
        this.saved = false;
        if (cursor > 1) this.jButtonPrevious.setEnabled(true);
        // Disable controls and notify if reached the end.
        if (cursor >= this.sentences.size()) {
            JOptionPane.showMessageDialog(this, "Reached the end of file.", "End of file", JOptionPane.INFORMATION_MESSAGE);
            this.disableControls();
        }
    }

    private int getSentenceType() {
        if (this.jRadioButtonSentenceNormal.isSelected()) {
            return 0;
        } else if (this.jRadioButtonSentenceHello.isSelected()) {
            return 1;
        } else if (this.jRadioButtonSentenceClosure.isSelected()) {
            return 2;
        } else if (this.jRadioButtonSentenceQuestionRebound.isSelected()) {
            return 3;
        } else if (this.jRadioButtonDontUnderstand.isSelected()) {
            return 4;
        } else {
            return 0;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupSentenceType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelOpened = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPos = new javax.swing.JTextField();
        jButtonGoToPos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSubmitted = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResponse = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaContextResponse = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jRadioButtonSentenceNormal = new javax.swing.JRadioButton();
        jRadioButtonSentenceHello = new javax.swing.JRadioButton();
        jRadioButtonSentenceClosure = new javax.swing.JRadioButton();
        jRadioButtonSentenceQuestionRebound = new javax.swing.JRadioButton();
        jRadioButtonSentencegetaround = new javax.swing.JRadioButton();
        jRadioButtonDontUnderstand = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpenXML = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jMenuItemGoPattern = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pimpy Teacher");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Opened file : ");
        jPanel1.add(jLabel1);

        jLabelOpened.setText("None");
        jPanel1.add(jLabelOpened);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(2, 20));
        jPanel1.add(jSeparator2);

        jLabel2.setText("Go to position :");
        jPanel1.add(jLabel2);

        jTextFieldPos.setEnabled(false);
        jTextFieldPos.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel1.add(jTextFieldPos);

        jButtonGoToPos.setText("Go");
        jButtonGoToPos.setEnabled(false);
        jButtonGoToPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoToPosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGoToPos);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Submitted sentence :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Response :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Context response :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel5, gridBagConstraints);

        jTextAreaSubmitted.setColumns(30);
        jTextAreaSubmitted.setLineWrap(true);
        jTextAreaSubmitted.setRows(3);
        jScrollPane1.setViewportView(jTextAreaSubmitted);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jTextAreaResponse.setColumns(30);
        jTextAreaResponse.setLineWrap(true);
        jTextAreaResponse.setRows(3);
        jScrollPane2.setViewportView(jTextAreaResponse);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        jTextAreaContextResponse.setColumns(30);
        jTextAreaContextResponse.setLineWrap(true);
        jTextAreaContextResponse.setRows(3);
        jScrollPane3.setViewportView(jTextAreaContextResponse);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        jPanel2.add(jScrollPane3, gridBagConstraints);

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Sentence type"));
        jPanel5.setLayout(new java.awt.GridLayout(2, 0));

        buttonGroupSentenceType.add(jRadioButtonSentenceNormal);
        jRadioButtonSentenceNormal.setSelected(true);
        jRadioButtonSentenceNormal.setText("Normal");
        jRadioButtonSentenceNormal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jRadioButtonSentenceNormal);

        buttonGroupSentenceType.add(jRadioButtonSentenceHello);
        jRadioButtonSentenceHello.setText("Hello");
        jRadioButtonSentenceHello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jRadioButtonSentenceHello);

        buttonGroupSentenceType.add(jRadioButtonSentenceClosure);
        jRadioButtonSentenceClosure.setText("Closure");
        jRadioButtonSentenceClosure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jRadioButtonSentenceClosure);

        buttonGroupSentenceType.add(jRadioButtonSentenceQuestionRebound);
        jRadioButtonSentenceQuestionRebound.setText("Question rebound");
        jRadioButtonSentenceQuestionRebound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jRadioButtonSentenceQuestionRebound);

        buttonGroupSentenceType.add(jRadioButtonSentencegetaround);
        jRadioButtonSentencegetaround.setText("Getaround");
        jRadioButtonSentencegetaround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jRadioButtonSentencegetaround);

        buttonGroupSentenceType.add(jRadioButtonDontUnderstand);
        jRadioButtonDontUnderstand.setText("Don't understand");
        jRadioButtonDontUnderstand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jRadioButtonDontUnderstand);

        jPanel4.add(jPanel5, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSave);

        jButtonPrevious.setText("Previous");
        jButtonPrevious.setEnabled(false);
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPrevious);

        jButtonNext.setText("Next");
        jButtonNext.setEnabled(false);
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonNext);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jMenuFile.setMnemonic('f');
        jMenuFile.setText("File");

        jMenuItemOpenXML.setText("Open XML conversation...");
        jMenuItemOpenXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenXMLActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpenXML);
        jMenuFile.add(jSeparator1);

        jMenuItemQuit.setMnemonic('q');
        jMenuItemQuit.setText("Quit");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemQuit);

        jMenuBar1.add(jMenuFile);

        jMenuTools.setMnemonic('t');
        jMenuTools.setText("Tools");

        jMenuItemGoPattern.setMnemonic('p');
        jMenuItemGoPattern.setText("Pattern teacher...");
        jMenuItemGoPattern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGoPatternActionPerformed(evt);
            }
        });
        jMenuTools.add(jMenuItemGoPattern);

        jMenuBar1.add(jMenuTools);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-641)/2, (screenSize.height-385)/2, 641, 385);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.controller.close();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
        this.formWindowClosing(null);
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    private void jMenuItemOpenXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenXMLActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            MSNLogParser parser = new MSNLogParser(file);
            try {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                parser.parse();
                this.setCursor(Cursor.getDefaultCursor());
                if (parser.getSentences().size() > 0) {
                    this.openedFile = file;
                    this.sentences = parser.getSentences();
                    this.cursor = 0;
                    this.saved = false;
                    this.jLabelOpened.setText(file.getName());
                    enableControls();
                    this.jButtonPrevious.setEnabled(false);
                    // Display the first message :
                    this.displayNext();
                } else {
                    JOptionPane.showMessageDialog(this, "This log file holds no messages.", "Error", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "An error occured while parsing XML:\n" + ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                this.setCursor(Cursor.getDefaultCursor());
            }
        } // User clicked cancel.
    }//GEN-LAST:event_jMenuItemOpenXMLActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        this.displayNext();
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        this.displayPrevious();
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // Sentence learning mechanism.
        // Not working if response or answer fields are empty.
        String submitted = this.jTextAreaSubmitted.getText();
        String answer = this.jTextAreaResponse.getText();
        String contextualAnswer = this.jTextAreaContextResponse.getText();
        if (submitted.isEmpty() || answer.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cannot save : Some of the fields are empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            // Check if this by chance would already exist in DB by checking answer existence :
            if (this.controller.checkExistenceByAnswer(answer)) {
                // This entry may already exist. Ask for confirmation...
                int rep = JOptionPane.showConfirmDialog(this, "This object might already exist. Save anyway ?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (rep == JOptionPane.NO_OPTION) {
                    return;
                }
            }
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            this.controller.learnNewSentence(submitted, answer, contextualAnswer, this.getSentenceType());
            this.setCursor(Cursor.getDefaultCursor());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQL error occured :\n" + ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            this.setCursor(Cursor.getDefaultCursor());
        }
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jMenuItemGoPatternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGoPatternActionPerformed
        JFramePatternTeacher pat = new JFramePatternTeacher(this.controller);
        pat.setLocationRelativeTo(null);
        pat.setVisible(true);
    }//GEN-LAST:event_jMenuItemGoPatternActionPerformed

    private void jButtonGoToPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoToPosActionPerformed
        if (this.sentences != null) {
            try {
                int pos = Integer.parseInt(this.jTextFieldPos.getText());
                if (pos >= this.sentences.size()) throw new NumberFormatException();
                this.cursor = (pos - 1);
                this.displayNext();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid position (not a number or out of file).", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonGoToPosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSentenceType;
    private javax.swing.JButton jButtonGoToPos;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelOpened;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemGoPattern;
    private javax.swing.JMenuItem jMenuItemOpenXML;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonDontUnderstand;
    private javax.swing.JRadioButton jRadioButtonSentenceClosure;
    private javax.swing.JRadioButton jRadioButtonSentenceHello;
    private javax.swing.JRadioButton jRadioButtonSentenceNormal;
    private javax.swing.JRadioButton jRadioButtonSentenceQuestionRebound;
    private javax.swing.JRadioButton jRadioButtonSentencegetaround;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextAreaContextResponse;
    private javax.swing.JTextArea jTextAreaResponse;
    private javax.swing.JTextArea jTextAreaSubmitted;
    private javax.swing.JTextField jTextFieldPos;
    // End of variables declaration//GEN-END:variables

}
